# Generated by Django 2.1.2 on 2018-10-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulo',
            old_name='imovel',
            new_name='unidade',
        ),
        migrations.RenameField(
            model_name='titulo',
            old_name='correcao',
            new_name='valor_correcao',
        ),
        migrations.AddField(
            model_name='titulo',
            name='tipo_correcao',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
