# Generated by Django 2.1.2 on 2018-10-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181027_0342'),
    ]

    operations = [
        #migrations.RenameModel(
        #    old_name='Imovel',
        #    new_name='Unidade',
        #),
        #migrations.RenameField(
        ##    model_name='unidade',
        #    old_name='codigo_unidade',
        #    new_name='codigo',
        #),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento_conjuge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
